### ISSUE TITLE
Cannot load native modules inside a webview element after a navigation

### ISSUE THREAD

**Issue by Shinryuuji** [atom/electron#1195]
My problem is mostly described in the title and can be easily reproduced with any native module. I use a webview element in which I load native modules that cannot be reloaded after a navigation request. I get the error message:
    
    Module did not self-register.

The module does work correctly before the navigation. This problem does not occur with the render process which created that webview. My guess is that the render process is re-created for each navigation request which in turn results in a new node instance. Calling `process.pid` always shows another id whereas the process id of the webview element does not change after a navigation.

As a side note: this problem is reproducible with NodeJS itself. I am therefore not quite sure if this is a problem that can be resolved by Atom Shell. Here is a small snippet that can be executed inside Atom Shell or a NodeJS application:

    require('<path to native module>');
    var path = require.resolve('<path to native module>');
    delete require.cache[path];
    require('<path to native module>');

I know that deleting an entry inside the `require.cache` property is not a good idea, but this simulates the behavior with a navigation pretty good. You can of course also just open the dev tools of the webview element and require a native module inside there, navigate somewhere else and require the same module again.

I have read the blog about [Multi-Context in node v0.12](https://strongloop.com/strongblog/whats-new-node-js-v0-12-multiple-context-execution/) (which I guess is also supported in iojs), and expected that already loaded native modules (shared libraries) can be reused across different node enviroments.

The reason why I am using a webview element instead of the rendering process itself is pretty easy. I dislike the white screen that is displayed for a short amount of time when I navigate to another page. That is probably due to the process being recreated on each navigation.

I guess I could also just load those native modules inside the browser process and just use the remote api to invoke them, thus preventing them from being reloaded after a navigation. However, I would like to prevent sharing them between all rendering process.

Is there a solution without loading those native modules inside the browser process and calling them through the remote api?

**Comment by zcbenz** [comment]
The design of Node's module system doesn't allow loading the same native module for multiple times in one process, so in atom-shell the renderer process is forced to restart when a page navigation happens or page is reloaded, in this way a page navigation would behave like restarting a Node process.

However in webview the renderer process doesn't restart for navigation or reloading, which prevented the native module to load when it has already been loaded in the same process.

Ideally the page in webview should behave the same with the page in BrowserWindow, but Chromium somehow treats it differently, I'm still looking into it.

**Comment by Shinryuuji** [comment]
I investigated a little further and found a comment inside node's source code: [Link](https://github.com/joyent/node/blob/v0.12.0/src/node.cc#L1986)

Seems like it's indeed a NodeJS problem with multi-contexts where node tries to reload shared libraries even though they were already loaded in another node environment.

Am unsure if this issue can be closed since it should resolve itself as soon as node fixes module loading.

**Comment by Shinryuuji** [comment]
Seems like it is working as intended when already loaded shared libraries do register themselves again in the new node environment. See the following diff patch for more details: 
https://gist.github.com/Shinryuuji/0aab152a0c431760868e

Am note sure if this could have any side effects. Any ideas?

**Comment by zcbenz** [comment]
@Shinryuuji Lots of native modules do not work correctly if you load them multiple times in the same process, because it is very likely their C++ code rely on some global states. So even your patch solved the module not loading problem, lots of native modules will still not work after a page navigation.

The correct solution is to force webview to restart render process on navigation, which behaves in the exact same way with Node/io.js.

**Comment by CharlieHess** [comment]
+1. This is kind of killing us in the Slack app.
