### ISSUE TITLE
oauth redirect fails

### ISSUE THREAD

**Issue by bhargavrpatel** [atom/electron#2123]
Hello,

I am currently trying to implement an OAuth2.0 API which requires a callback URI. I tested the auth path, and the params in Postman as well as a regular Chrome window.

When following the same process done by others with Github API. I am not getting forwarded to the callback url. The auth page simply refreshes. I also logged the response as well as redirect triggers. Nothing useful.

My code is identical to theirs! Only difference is the URL. What can be the cause of this? Has there been any recent updates that make their code useless?

Thanks,
B

**Comment by bhargavrpatel** [comment]
Video of the flow of events (failing)
https://vid.me/Re4G

**Comment by zcbenz** [comment]
Can you make sure you are using latest Electron? Some old versions do not work well with POST requests.

**Comment by bhargavrpatel** [comment]
Upgrades from 0.27 to latest and the problem is solved. 
Thanks.

**Comment by samerbekhazi** [comment]
I am using the latest version 0.30.2 and I am not able to authenticate on facebook. The page is stuck after logging in. I tried various websites, almost all didn't work, except SoundCloud.
Is there anything that I should add in electron regarding authentication?

To reproduce:
app.on('ready', function() {
  mainWindow = new BrowserWindow({title:'Title', show: true});
  mainWindow.loadUrl('https://www.deezer.com/');
}

I also tried with node-integration set to false, same issue.

**Comment by bhargavrpatel** [comment]
@samerbekhazi give it dimensions such that
```javascript
app.on('ready', function() {
  mainWindow = new BrowserWindow({height: 500, width: 500, title:'Title', show: true});
  mainWindow.loadUrl('https://www.deezer.com/');
}
```

**Comment by samerbekhazi** [comment]
It's still not working. Let me clarify: The initial page opens without any issue (deezer.com) but when I try to authenticate via facebook (let's say, sign up) the authentication is stuck after logging in. Btw I'm testing on Ubuntu 14.04 if it matters at all.

**Comment by markbaas** [comment]
@samerbekhazi did you ever solve the problem?

**Comment by bhargavrpatel** [comment]
This whole thing is a bit too magical for my taste.
