### ISSUE TITLE
Getting "garbage" back when using http protocol interception with webview

### ISSUE THREAD

**Issue by alexindigo** [atom/electron#2303]
Trying to intercept `http` protocol and do nothing.

main.js:

```

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function()
{

  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1200, height: 800, frame: true, center: true});

  // interesting that I can't require protocol module before
  var protocol = require('protocol');

  protocol.interceptProtocol('http', function(req)
  {
    console.log('\n\nGOT HTTP', req.method, req.url, req.referrer, '\n\n');
    return null;
  });

  mainWindow.loadUrl('file://' + __dirname + '/index.html');
``` 

index.html:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Loading...</title>
    <script src="chrome.js"></script>
  </head>
  <body>
    <webview class="content"></webview>
  </body>
</html>
```

chrome.js:

```
window.addEventListener('DOMContentLoaded', function()
{
   var content = document.querySelector('.content');
   content.src = 'http://www.trulia.com';
}, false);
```

And when app is loaded I'd get following in the webview: 
![garbage](http://ia.gs/c1ga/Image%202015-07-22%20at%2012.22.46%20PM.png)

If there is no protocol intercept page loads normally.

Thank you.

**Comment by deepak1556** [comment]
@zcbenz this should be fixed in https://github.com/atom/electron/pull/2298

**Comment by alexindigo** [comment]
Thank you @deepak1556.
I still think though that my main problem is not understanding protocol module docs well enough. :)

**Comment by deepak1556** [comment]
@alexindigo which part of the docs is not clear ?

**Comment by alexindigo** [comment]
Funny part is that there is no simple (and non-obtrusive) example, just to see what's going on. :)

It took me some time of crawling through issues here to find this syntax :)

```
 protocol.interceptProtocol('http', function(req)
  {
    console.log('\n\nGOT HTTP', req.method, req.url, req.referrer, '\n\n');
    return null;
  });
```

And I'm still not sure if it's correct. :)

And the fact that I need to require `protocol` module after app is ready (and maybe after MainWindow is created), makes debugging more challenging as well. :)

**Comment by deepak1556** [comment]
> (and maybe after MainWindow is created)

Its not required, the async api fixes it  and your usage is correct with the old api. The new api is `protocol.interceptProtocol(scheme, handler, callback)`

```
 protocol.interceptProtocol('http', function(req) {
    console.log('\n\nGOT HTTP', req.method, req.url, req.referrer, '\n\n');
    return null;
 }, function(error, scheme) {
    if (!error)
      console.log(scheme, 'intercepted successfully');
});
```

Feel free to send a PR to update docs with examples if something is not clear :)

**Comment by alexindigo** [comment]
Just to clarify, I still need to require protocol after app is ready, but I can do it before I initialize the main window. Or can I require protocol as any other module?

Thanks for the example. I'll submit it to the docs.

**Comment by deepak1556** [comment]
> Just to clarify, I still need to require protocol after app is ready, but I can do it before I initialize the main window.

Yup, you can use it just like any other module of the main process that are available after app is ready.

```
var app = require('app'),
    BrowserWindow = require('browser-window');

var mainWindow = null;

app.on('ready', function() {
  var protocol = require('protocol');
  protocol.interceptProtocol('http', function(request){ }, function(error, scheme) {
    mainWindow.loadUrl(...);
    mainWindow.openDevTools({detach: true});
  });
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });
});
```

**Comment by alexindigo** [comment]
Thanks for the examples. Although they don't work me. (I updated electron to 0.30.1).

Most working state when I do protocol thing after creation of MainWindow. And it dies when I'm navigating to the new page within webview. Without anything in the logs.

When I ran your example carbon-copy, this is what I've got: `[Error: The Scheme does not exist.]`

**Comment by deepak1556** [comment]
@alexindigo could you provide a sample thats causing to break protocol interception on navigation in webview ? I tried quite a few sites in webview and all seem to work fine.
