### ISSUE TITLE
G-Sync monitor create a huge lag when using electron based applciations

### ISSUE THREAD

**Issue by ice-blaze** [atom/electron#2767]
__Monitors tested__: Asus ROG pg278q, Acer XB280HK
__OS tested__: Windows 7, Windows 10
***
There is already an issue opened on the atom repository: https://github.com/atom/atom/issues/8755
***
There is already a thread opened on the atom forums: https://discuss.atom.io/t/g-sync-windowed-screen-very-slow/20696/12

**Comment by zcbenz** [comment]
The Electron used by Atom is a bit old for now, the next release of Atom will include Electron v0.29.x, and  there is also a PR(https://github.com/atom/atom/pull/8779) to update Electron to the latest one.

Considering G-Sync is relatively new, this is very likely to have been fixed by recent Chrome versions (e.g. recent Electron versions), so I'm closing this issue in Electron, but if the problem still exists after https://github.com/atom/atom/pull/8779 gets merged, I'll reopen the issue here.

**Comment by bording** [comment]
I just tested Atom 1.6.1 on a Windows machine that has two G-Sync enabled monitors, and I'm still seeing this performance problem.

I've tested the following applications that use Electron, and they are all exhibiting the same behavior:

- Atom 1.6.1
- VS Code 0.10.11
- GitHub Desktop 3.0.16.0

I don't have this problem in Chrome itself, currently running Version 49.0.2623.110 m (64-bit).

**Comment by bording** [comment]
I also just tried out the [quick start app](https://github.com/atom/electron-quick-start) and updated package.json to reference 0.37.3 instead, and I'm seeing the exact same problem there.

At this point, I think it is safe to say that the latest electron hasn't fixed this problem, so this issue should be re-opened!

**Comment by zcbenz** [comment]
It is being tracked at #3026.

**Comment by bording** [comment]
Ah, I didn't see that one when I searched before, thanks!
